from homework import some_function


# try:
#     from non_existent_module import some_function
# except ImportError as e:
#     print(f"Caught an exception: {e}")


# def something(parameter):
#     try:
#         with open(parameter, 'r') as file:
#             data = file.read()
#             return data
#     except FileNotFoundError as e:
#         return f"Такого файлу нема: {e}"
#
#
# print(something("get_digits_from_random_text_.txt"))
